; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf

monitor_speed = 115200
upload_speed = 921600

# Force the physical layout definition
board_build.flash_size = 16MB

# Force the partitions configuration file
board_build.partitions = partitions.csv

# ADD THESE LINES TO FORCE CHIP REGISTERS:
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216

build_flags =
    -DBOARD_HAS_PSRAM

lib_deps =
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^7.0.4

# Enable PMKSA caching (Crucial for fast re-association)
CONFIG_ESP_WIFI_PMKSA_SUPPORT=y

# Enable 802.11k (Radio Resource Management / Neighbor Report)
CONFIG_ESP_WIFI_80211K_SUPPORT=y

# Enable 802.11v (BSS Transition Management)
CONFIG_ESP_WIFI_80211V_SUPPORT=y